linters:
  enable-all: true
  disable:
    - lll
    - varnamelen
    - wrapcheck
    - err113
    - gochecknoglobals
    - exhaustruct
    - cyclop
    - funlen
    - gocognit
    - gocyclo
    - testpackage
    - depguard
    - gomnd
    - mnd
    - execinquery
    - maintidx

linters-settings:
  tagliatelle:
    case:
      rules:
        json: snake
